ClientApplicationMVC/Controllers/CompanyListingsController.cs
using ClientApplicationMVC.Models;

using Messages.DataTypes.Database.CompanyDirectory;
using Messages.ServiceBusRequest.CompanyDirectory.Responses;
using Messages.ServiceBusRequest.CompanyDirectory.Requests;

using System;
using System.Web.Mvc;
using System.Web.Routing;
using System.Net.Http;
using System.Web.Script.Serialization;
using System.Text;
using System.Collections.Generic;
using Messages.ServiceBusRequest.Weather.Requests;
using Messages.DataTypes.Database.Weather;
using Messages.ServiceBusRequest.Weather.Responses;

namespace ClientApplicationMVC.Controllers
{
    /// <summary>
    /// This class contains the functions responsible for handling requests routed to *Hostname*/CompanyListings/*
    /// </summary>
    public class CompanyListingsController : Controller
    {
        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings
        /// </summary>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult Index()
        {
            if (Globals.isLoggedIn())
            {
                ViewBag.Companylist = null;
                return View("Index");
            }
            return RedirectToAction("Index", "Authentication");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/Search
        /// </summary>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult Search(string textCompanyName)
        {

            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if(connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            CompanySearchRequest request = new CompanySearchRequest(textCompanyName);

            CompanySearchResponse response = connection.getCompanies(request);
            if (response.result == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.Companylist = response.list;

            return View("Index");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/DisplayCompany/*info*
        /// </summary>
        /// <param name="id">The name of the company whos info is to be displayed</param>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult DisplayCompany(string id)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if ("".Equals(id))
            {
                return View("Index");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.CompanyName = id;
            GetCompanyInfoRequest infoRequest = new GetCompanyInfoRequest(new CompanyInstance(id));
            GetCompanyInfoResponse infoResponse = connection.getCompanyInfo(infoRequest);

            if (infoResponse.result)
            {
                ViewBag.CheckReviews = true;
                ViewBag.CompanyInfo = infoResponse.companyInfo;
                if (infoResponse.companyInfo.reviewList.reviews == null)
                {
                    ViewBag.CheckReviews = false;
                }
                else
                {
                    List<ReviewInstance> r = infoResponse.companyInfo.reviewList.reviews;
                    string[] timestamp_readable = new string[r.Count];
                    
                    for (int i = 0; i < timestamp_readable.Length; i++)
                    {
                        System.DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
                        dtDateTime = dtDateTime.AddSeconds(Convert.ToInt64(r[i].timestamp)).ToLocalTime();
                        timestamp_readable[i] = Convert.ToString(dtDateTime);
                    }
                    ViewBag.Timestamp = timestamp_readable;
                }
            }

            //Still assume location array is of one value.
            GetWeatherRequest weatherRequest = new GetWeatherRequest(new CompanyWeather { location = infoResponse.companyInfo.locations[0] });
            GetWeatherResponse weatherResponse = connection.getWeather(weatherRequest);
            if (!weatherResponse.result)
                ViewBag.success = false;
            else
            {
                ViewBag.success = true;
                ViewBag.realFeel = weatherResponse.companyWeather.realFeelTemperature;
                ViewBag.temp = weatherResponse.companyWeather.temperature;
                ViewBag.weatherText = weatherResponse.companyWeather.weatherText;
            }

            return View("DisplayCompany");
        }

        public ActionResult SaveReview(string textUserReview, string rating, string companyName)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }
            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ReviewInstance review = new ReviewInstance(companyName, textUserReview , Convert.ToInt32(rating),
                DateTimeOffset.Now.ToUnixTimeSeconds(), Globals.getUser());
            SaveCompanyReviewRequest request = new SaveCompanyReviewRequest(review);
            SaveCompanyReviewResponse response = connection.saveCompanyReview(request);

            return RedirectToAction("DisplayCompany", new { id = companyName });
        }
    }
}

ClientApplicationMVC/Views/CompanyListings/DisplayCompany.cshtml
<link href="~/Content/ChatStyles.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/CompanyListings/CompanyListingsFunctions.js"></script>
<h2 id="CompanyNameDisplay">@ViewBag.CompanyName</h2>
<br />
<p>Email: @ViewBag.CompanyInfo.email</p>
<p>Phone Number: @ViewBag.CompanyInfo.phoneNumber</p>
<p>@ViewBag.CompanyName can be found at these locations:</p>
@foreach (string location in ViewBag.CompanyInfo.locations)
{
    <p style="padding-left:4em;">@location</p>
    <br />
}

<br />

@if((bool)ViewBag.success)
{ 
<div style="border-top: thin solid gray; border-bottom: thin solid gray;" class="row">
    <div class="col-md-10">
        @{ 
        string temp = (string)ViewBag.weatherText;
        //Put in all lowercase to guarantee correctness.
        temp = temp.ToLower();
        switch(temp)
        {
            case (@"sunny"):
                <img src="~/Content/Weather_Icons/sunny.png" width="50" height="50" />
                break;

            case (@"mostly sunny"):
                <img src="~/Content/Weather_Icons/sunny.png" width="50" height="50" />
                break;

            case (@"partly sunny"):
                <img src="~/Content/Weather_Icons/sunny.png" width="50" height="50" />
                break;

            case (@"intermittent clouds"):
                <img src = "~/Content/Weather_Icons/mostlycloud.png" width = "50" height = "50" />
                break;

            case (@"hazy sunshine"):
                <img src="~/Content/Weather_Icons/mostlycloud.png" width="50" height="50" />
                break;

            case (@"mostly cloudy"):
                <img src="~/Content/Weather_Icons/mostlycloud.png" width="50" height="50" />
                break;

            case (@"cloudy"):
                <img src="~/Content/Weather_Icons/mostlycloud.png" width="50" height="50" />
                break;

            case (@"dreary (overcast)"):
                <img src="~/Content/Weather_Icons/mostlycloud.png" width="50" height="50" />
                break;
           
            case (@"showers"):
                <img src="~/Content/Weather_Icons/rain.png" width="50" height="50" />
                break;

            case (@"mostly cloudy w/ showers"):
                <img src="~/Content/Weather_Icons/rain.png" width="50" height="50" />
                break;
            
            case (@"partly sunny w/ showers"):
                <img src="~/Content/Weather_Icons/rain.png" width="50" height="50" />
                break;
            
            case (@"t-storms"):
                <img src="~/Content/Weather_Icons/rain.png" width="50" height="50" />
                break;

            case (@"mostly cloudy w/ t-storms"):
                <img src="~/Content/Weather_Icons/rain.png" width="50" height="50" />
                break;
            
            case (@"partly sunny w/ t-storms"):
                <img src="~/Content/Weather_Icons/rain.png" width="50" height="50" />
                break;
            
            case (@"snow"):
                <img src="~/Content/Weather_Icons/snow.png" width="50" height="50" />
                break;
            
            case (@"mostly cloudy w/ snow"):
                <img src="~/Content/Weather_Icons/snow.png" width="50" height="50" />
                break;
            
            case (@"ice"):
                <img src="~/Content/Weather_Icons/snow.png" width="50" height="50" />
                break;
            
            case (@"sleet"):
                <img src="~/Content/Weather_Icons/snow.png" width="50" height="50" />
                break;
            
            case (@"freezing rain"):
                <img src="~/Content/Weather_Icons/snow.png" width="50" height="50" />
                break;

            case (@"rain and snow"):
                <img src="~/Content/Weather_Icons/snow.png" width="50" height="50" />
                break;

            default:
                <img src="~/Content/Weather_Icons/no.png" width="50" height="50"/>
                break;
        }
        }
        <span style="font: bold; color: seagreen">Real Feel Temperature:</span> @ViewBag.realFeel °C
        <span style="font: bold; color: seagreen">Temperature:</span> @ViewBag.temp °C
        <span style="font: bold; color: seagreen">Weather:</span> @ViewBag.weatherText
    </div>
</div>
 }
else
{
    <p>An error occurred when fetching weather information for this company.</p>
    <p>Please ensure that the location of the company is valid.</p>
}

<br />

<div style="height:100px">
    <h4>Start a conversation with @ViewBag.CompanyName</h4>
    <div style="width:350px; float:left">
        <textarea class="messagetextarea" id="textUserMessage" placeholder="Enter your message here." rows="2" cols="25"></textarea>
    </div>
    <div style="float:left">
        <button class="sendbutton" id="SendMessageButton">Send</button>
    </div>
</div>
<br />
@using (Html.BeginForm("SaveReview", "CompanyListings", FormMethod.Post))
{
<div style="height:150px">
    <h4>Write a Review for @ViewBag.CompanyName</h4>
    <div style="width:100px; float:left, ">
        <textarea class="messagetextarea" name="textUserReview" placeholder="Enter your review here." rows="3" cols="35"></textarea>
    </div>
    <div style="width:30px; float:left">
        <p>Rating: </p>
    </div>
    <div style="width:300px;float:left; margin-left:20px">
        <select name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
    </div>
    <div style="float:left">
        <button class="savebutton" id="SaveReviewButton">Save</button>
    </div>
    <input type="hidden" name="companyName" value=@ViewBag.CompanyName />
</div>
}
<br /><br />


<h4>@ViewBag.CompanyName's Reviews</h4>
@if (ViewBag.CheckReviews)
{
    int i = 0;
    foreach (var review in ViewBag.CompanyInfo.reviewList.reviews)
    {
        <p>Username: @review.userName | Timestamp: @ViewBag.Timestamp[i] | Stars: @review.stars/5</p>
        <p style="padding-left:4em;">Review: @review.review</p>
        <br />
        i = i + 1;
    }
}
else
{
    <p>
        @ViewBag.CompanyInfo.reviewList.response
    </p>
    <br />
}

ClientApplicationMVC/Views/CompanyListings/Index.cshtml
<script type="text/javascript" src="~/Scripts/CompanyListings/CompanyListingsFunctions.js"></script>
<!--
    This page will be used to search for and display Company names
-->
@{
    ViewBag.Title = "Index";
}


@using (Html.BeginForm("Search", "CompanyListings", FormMethod.Get,
    new { id = "searchForm", onsubmit = "return validateSearchEntry()" }))
{
    <h2>Search for companies by name</h2>

    <p>@ViewBag.Message</p>
    <br />

    @Html.TextBox("textCompanyName", "", new {required = "TRUE", pattern = "[a-zA-Z0-9]{2,15}", title = "Search entry must be 2-15 alphanumeric characters"})
    <input type="submit" name="searchButton" value="Search"/>
    <br /><br /><br />

}
@if (ViewBag.Companylist != null)
{
    if (ViewBag.Companylist.companyNames.Length == 0)
    {
        <p>Your search did not return any results. Please try again.</p>
    }
    else
    {
        <p style="font-size:larger">Results:</p> <br />
        foreach (string item in ViewBag.Companylist.companyNames)
        {
            @Html.ActionLink(item, "DisplayCompany/" + item, "CompanyListings")
            <br />
        }
    }
}